<?php

return [
    "sidebar_permissions" =>  [
        "sidebar_whatsapp" => "whatsapp",
    ],
    "manufacturing_module" => [
        "production-view" => "Production List",
        "production-add" => "Add Production",
        "production-edit" => "Edit Production",
        "production-delete" => "Delete Production",
        "recipe-view" => "Recipe List",
        "recipe-add" => "Add Recipe",
        "recipe-edit" => "Edit Recipe",
        "recipe-delete" => "Delete Recipe",
    ],
    "restaurant_module" => [
        "restaurant-floor" => "Floors",
        "restaurant-table" => "Tables",
        "restaurant-reservation" => "Reservation",
        "restaurant-menu-type" => "Menu Type",
        "restaurant-modifier-group" => "Modifier Group",
        "restaurant-kitchen" => "Kitchen",
        "restaurant-kitchen-dashboard" => "Kitchen Dashboard",
        "restaurant-pos" => "Restaurant POS",
    ],
    "tailoring_module" => [
        "tailoring-dashboard" => "Tailoring Dashboard",
        "tailoring-measurements-index" => "Measurement Profiles",
        "tailoring-measurements-add" => "Add Measurement Profile",
        "tailoring-measurements-edit" => "Edit Measurement Profile",
        "tailoring-measurements-delete" => "Delete Measurement Profile",
        "tailoring-orders-index" => "Tailoring Orders",
        "tailoring-orders-add" => "Add Tailoring Order",
        "tailoring-orders-edit" => "Edit Tailoring Order",
        "tailoring-orders-delete" => "Delete Tailoring Order",
        "tailoring-order-payments-add" => "Add Tailoring Advance Payment",
        "tailoring-templates-index" => "Garment Templates",
        "tailoring-templates-add" => "Add Garment Template",
        "tailoring-templates-edit" => "Edit Garment Template",
        "tailoring-templates-delete" => "Delete Garment Template",
        "tailoring-materials-manage" => "Manage Tailoring Materials",
        "tailoring-production-board" => "Production Board",
        "tailoring-notifications-manage" => "Manage Notification Templates",
        "tailoring-notifications-send" => "Send Tailoring Notifications",
        "tailoring-delivery-manage" => "Delivery and Final Sale",
        "tailoring-reports" => "Tailoring Reports",
        "tailoring-trials-view" => "View Tailoring Trials",
        "tailoring-trials-schedule" => "Schedule Tailoring Trials",
        "tailoring-trials-complete" => "Complete Tailoring Trials",
        "tailoring-alterations-manage" => "Manage Tailoring Alterations",
        "tailoring-alterations-approve" => "Approve Tailoring Alterations",
        "tailoring-catalog.view" => "View Tailoring Catalog",
        "tailoring-catalog.manage" => "Manage Tailoring Catalog",
        "tailoring.collection.manage" => "Manage Tailoring Collections",
        "tailoring.style.manage" => "Manage Tailoring Styles",
        "tailoring.style_version.activate" => "Activate Tailoring Style Versions",
        "tailoring.component_role.manage" => "Manage Tailoring Component Roles",
        "tailoring.order.price_override" => "Override Tailoring Order Price",
    ],
    "social_commerce_module" => [
        "view social commerce" => "Social Commerce Dashboard",
        "manage social catalogue" => "Manage Social Commerce Catalogue",
        "manage social commerce settings" => "Manage Social Commerce Settings",
    ],
    "project_module" => [
        "project_project_list" => "Project List",
        "project_project_add" => "Project Add",
        "project_project_show" => "Project Show",
        "project_project_edit" => "Project Edit",
        "project_project_delete" => "Project Delete",
        "project_task_list" => "Task List",
        "project_task_add" => "Task Add",
        "project_task_show" => "Task Show",
        "project_task_edit" => "Task Edit",
        "project_task_delete" => "Task Delete",
        "project_category_list" => "Project Category List",
        "project_category_add" => "Project Category Add",
        "project_category_edit" => "Project Category Edit",
        "project_category_delete" => "Project Category Delete",
    ],
    "repair_module" => [
        "repair-dashboard" => "Repair Dashboard",
        "repair-service-index" => "service_jobs_list",
        "repair-service-view" => "view_service_jobs",
        "repair-service-add" => "add_service_job",
        "repair-service-edit" => "edit_service_job",
        "repair-service-delete" => "delete_service_job",
        "repair-parts-view" => "View Parts and Billing",
        "repair-parts-add" => "Add Part",
        "repair-parts-edit" => "Edit Parts Qty bi Price",
        "repair-parts-delete" => "Remove Parts",
        "repair-charges-edit" => "Edit Service Charges",
        "repair-payment-add" => "Collect Payment",
        "repair-payment-delete" => "Delete Payment",
        "repair-device-type" => "Device Type",
    ]
];